name: dotnet-desktop

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: StatisticsCW/StatisticsCW.csproj
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: .NET Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: .NET Build
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -p:PublishSingleFile=true --no-restore

      - name: .NET Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build
        
      - name: Create release ZIP archive
        run: tar.exe acvf Release.zip -C .\StatisticsCW\bin\Release\net7.0-windows\win-x64\publish\ --strip-components=1 .      

      - name: Create release 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref_name }}
          title: ${{ github.ref_name }}
          prerelease: false
          files: ./Release.zip